updateDocsComment: >
  Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes.
requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!
requestInfoLabelToAdd: request-more-info

newPRWelcomeComment: >
  Thanks so much for opening your first PR here!
firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada: How awesome!
newIssueWelcomeComment: >
  Thanks for opening this issue, a maintainer will get back to you shortly!
sentimentBotToxicityThreshold: .7

sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users. cc/ @MrKrishnaAgarwal
lockThreads:
  toxicityThreshold: .7
  numComments: 2
  setTimeInHours: 72
  replyComment: >
    This thread is being locked due to exceeding the toxicity minimums. cc/ @MrKrishnaAgarwal
  lockLabelToAdd: lock

blank_issues_enabled: false
contact_links:
  - name: ğŸ“ Website
    url: https://mrkrishna.me
    about: Visit my website to learn more about me!

  - name: ğŸ“§ Email
    url: mailto:dmkrishna.agarwal@gmail.com

  - name: ğŸ¦ Twitter
    url: https://twitter.com/DMKrishnaA
    about: Follow me on Twitter to get the latest updates!

  - name: ğŸ“¸ Dev.to
    url: https://dev.to/krishnaagarwal
    about: Follow me on Dev.to to see my latest posts!

  - name: ğŸ˜º GitHub
    url: https://github.com/MrKrishnaAgarwal
    about: Follow me on GitHub to view my latest projects!
