name: gitartwork from contribution graph

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the imgbot branch
  push:
    branches: [ imgbot ]
  pull_request:
    branches: [ imgbot ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jasineri/gitartwork@v1
        with:
           # Use this username's contribution graph  
           user_name: Shougo
           # Text on contribution graph 
           text: KRISHNA
      - uses: jasineri/simple-push-action@v1
  # This workflow contains a single job called "build"
 
